### ISSUE TITLE
Dropdown menus don't show up if their height is larger than the viewport's height

### ISSUE THREAD

**Issue by PedroSapichu** [OkunaOrg/okuna-web#73]
Hi! 

Currently, the dropdown menu (by the username) only works when you are at the very top of the timeline. I think it should work elsewhere:

![image](https://user-images.githubusercontent.com/25947175/88805634-65f69f00-d17d-11ea-84d2-5ebab8fd1496.png)

It also seems that once the menu is active (if clicked) it "sticks" to the very top of the timeline, so when scrolling down it dissapears, maybe it should stick to whatever position the user is at?

**Comment by Komposten** [comment]
What browser are you using?

It's working for me using Vivaldi:
![image](https://user-images.githubusercontent.com/7335682/88807524-2007fe00-d1b2-11ea-87a1-7924b1562e40.png)

**Comment by PedroSapichu** [comment]
Mozilla Firefox (79.0 -latest edition) on a Windows 10 laptop.

**Comment by Komposten** [comment]
Hmm, it seems to work in Firefox 79 for me. However, as soon as I open dev tools it jumps up to the top and sticks there, sometimes above the screen. 🤔

**Comment by ChrisSasis** [comment]
Same with Microsoft Edge.

**Comment by Komposten** [comment]
Got another report of something similar that mentioned windowed mode. I put my browser in windowed mode and could immediately reproduce the bug. It seems like the "menu sticks to the top of screen" feature breaks if the window isn't tall enough to fit the menu properly.

**Comment by jozsefsallai** [comment]
The issue seems to happen because the dropdown uses the CSS translate3d feature to set the position of the dropdown and for some reason it changes the Y position from 84px to 5px if the dropdown's height is bigger than the viewport's height. This might be an upstream issue with v-tooltip. We can probably hardcode some overrides to mitigate the issue but I feel like there's an option that we can pass to the popover constructor that disables this behavior.
